### ISSUE TITLE
Error due to null table name after upgrading core to 5.69

### ISSUE THREAD

**Issue by angusfretwell** [systopia/de.systopia.eck#104]
Since upgrading to 5.69, a fatal error is thrown after clearing the cache with `cv flush`. Subsequent requests don't produce this error. It seems to be related to a custom field I have on activities pointing at an ECK entity.

Here's the error and stack trace:

```
The website encountered an unexpected error. Try again later.

TypeError: CRM_Core_DAO_AllCoreTables::getTableForEntityName(): Return value must be of type string, null returned in CRM_Core_DAO_AllCoreTables::getTableForEntityName() (line 365 of /var/www/html/vendor/civicrm/civicrm-core/CRM/Core/DAO/AllCoreTables.php).
Civi\Api4\Service\Schema\SchemaMapBuilder::getTableName('Eck_Campaign') (Line: 149)
Civi\Api4\Service\Schema\SchemaMapBuilder->addCustomFields(Object, Object, 'Activity') (Line: 74)
Civi\Api4\Service\Schema\SchemaMapBuilder->loadTables(Object) (Line: 52)
Civi\Api4\Service\Schema\SchemaMapBuilder->build() (Line: 309)
Civi\Api4\Utils\CoreUtil::getSchemaMap() (Line: 773)
Civi\Api4\Query\Api4SelectQuery->autoJoinFK('dashboard_contact.id') (Line: 183)
Civi\Api4\Query\Api4SelectQuery->buildSelectClause() (Line: 79)
Civi\Api4\Query\Api4Query->getSql() (Line: 90)
Civi\Api4\Query\Api4Query->getResults() (Line: 106)
Civi\Api4\Query\Api4SelectQuery->run() (Line: 107)
Civi\Api4\Generic\DAOGetAction->getObjects(Object) (Line: 94)
Civi\Api4\Generic\DAOGetAction->_run(Object) (Line: 72)
Civi\Api4\Provider\ActionObjectProvider->invoke(Object) (Line: 156)
Civi\API\Kernel->runRequest(Object) (Line: 256)
Civi\Api4\Generic\AbstractAction->execute() (Line: 91)
civicrm_api4('Dashboard', 'get', Array) (Line: 69)
CRM_Core_BAO_Dashboard::getContactDashlets() (Line: 46)
CRM_Contact_Page_DashBoard->run(Array, NULL) (Line: 322)
CRM_Core_Invoke::runItem(Array) (Line: 69)
CRM_Core_Invoke::_invoke(Array) (Line: 36)
CRM_Core_Invoke::invoke(Array) (Line: 88)
Drupal\civicrm\Civicrm->invoke(Array) (Line: 83)
Drupal\civicrm\Controller\CivicrmController->main(Array, '')
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 627)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 121)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by colemanw** [comment]
I'm seeing something similar. On my test site I have an ECK type called "Food". It doesn't have any custom fields.
Every time I run `cv flush` on the command line and refresh the page I see this once:

> CRM_Core_Exception: Entity not loaded: Eck_Food in `Civi\Api4\Service\Spec\SpecGatherer->getDAOFields()` (line 269 of `Civi/Api4/Service/Spec/SpecGatherer.php`).

Refresh the page again and the error goes away & everything works fine. Feels like a load-order issue when the container is being rebuilt, but I haven't investigated further.

I suspect what you're seeing has the same cause but a different symptom since your entity does have custom fields.

**Comment by angusfretwell** [comment]
I'm also seeing this come up as an `UnauthorizedException` if an unauthenticated user makes the first request after caches are cleared. This doesn't resolve after refreshing.


```
Civi\API\Exception\UnauthorizedException: Authorization failed in Civi\API\Kernel->authorize() (line 230 of /var/www/html/vendor/civicrm/civicrm-core/Civi/API/Kernel.php).
Civi\API\Kernel->runRequest(Object) (Line: 256)
Civi\Api4\Generic\AbstractAction->execute() (Line: 91)
civicrm_api4('Eck_Phonebank', 'getFields', Array) (Line: 149)
Civi\Eck\API\Entity::getEckAfforms(Object, 'civi.afform.get', Object)
call_user_func_array(Array, Array) (Line: 53)
Civi\Core\Event\ServiceListener->__invoke(Object, 'civi.afform.get', Object) (Line: 220)
Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'civi.afform.get', Object) (Line: 56)
Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object, 'civi.afform.get') (Line: 263)
Civi\Core\CiviEventDispatcher->dispatch('civi.afform.get', Object) (Line: 43)
Civi\Api4\Action\Afform\Get->getRecords() (Line: 51)
Civi\Api4\Generic\BasicGetAction->_run(Object) (Line: 72)
Civi\Api4\Provider\ActionObjectProvider->invoke(Object) (Line: 156)
Civi\API\Kernel->runRequest(Object) (Line: 256)
Civi\Api4\Generic\AbstractAction->execute() (Line: 315)
_afform_hook_civicrm_angularModules(Object, 'hook_civicrm_angularModules', Object) (Line: 220)
Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'hook_civicrm_angularModules', Object) (Line: 56)
Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object, 'hook_civicrm_angularModules') (Line: 263)
Civi\Core\CiviEventDispatcher->dispatch('hook_civicrm_angularModules', Object) (Line: 168)
CRM_Utils_Hook->invoke(Array, Array, NULL, NULL, NULL, NULL, NULL, 'civicrm_angularModules') (Line: 2715)
CRM_Utils_Hook::angularModules(Array) (Line: 94)
Civi\Angular\Manager->getModules() (Line: 191)
Civi\Angular\Manager->resolveDefaultModules('civicrm/event/register') (Line: 271)
Civi\Angular\AngularLoader->findActiveModules() (Line: 131)
Civi\Angular\AngularLoader->loadAngularResources() (Line: 391)
Civi\Angular\AngularLoader->onRegionRender(Object, 'civi.region.render', Object)
call_user_func_array(Array, Array) (Line: 53)
Civi\Core\Event\ServiceListener->__invoke(Object, 'civi.region.render', Object) (Line: 220)
Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'civi.region.render', Object) (Line: 56)
Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object, 'civi.region.render') (Line: 263)
Civi\Core\CiviEventDispatcher->dispatch('civi.region.render', Object) (Line: 64)
CRM_Core_Region->render('') (Line: 37)
civicrm_page_attachments(Array) (Line: 311)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}(Object, 'civicrm') (Line: 388)
Drupal\Core\Extension\ModuleHandler->invokeAllWith('page_attachments', Object) (Line: 308)
Drupal\Core\Render\MainContent\HtmlRenderer->invokePageAttachmentHooks(Array) (Line: 285)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 627)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 284)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 128)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 186)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by jensschuppe** [comment]
> I'm seeing something similar. On my test site I have an ECK type called "Food". It doesn't have any custom fields. Every time I run `cv flush` on the command line and refresh the page I see this once:
> 
> > CRM_Core_Exception: Entity not loaded: Eck_Food in `Civi\Api4\Service\Spec\SpecGatherer->getDAOFields()` (line 269 of `Civi/Api4/Service/Spec/SpecGatherer.php`).
> 
> Refresh the page again and the error goes away & everything works fine. Feels like a load-order issue when the container is being rebuilt, but I haven't investigated further.

This is basically a hen-and-egg problem I guess, because `CRM_Core_DAO_AllCoreTables::getBaoClasses()` is being called for auto-registering event listeners via `EventSubscriberInterface` or `HookInterface` implementations in https://github.com/civicrm/civicrm-core/commit/c8d8465306767fe281283ed005f1f1cb86d0f7c1#diff-4f4d71cf8bcad044570b79ff938e54e9695649ee124b96a6fcfc5e1ef36f555fR343. ECK entity types, however, are only registered through such an auto-subscribed event listener and are missing in `AllCoreTables`' entity type cache at that point.

We could:
1. manually register the `hook_civicrm_entityTypes` listener
2. let core `\CRM_Core_DAO_AllCoreTables::flush()` after auto-subscribed BAO listeners have been registered [here](https://github.com/civicrm/civicrm-core/blob/3cab30bb5bf1be43f460b454ab453d5da5e3ac32/Civi/Core/Container.php#L409) - I opened civicrm/civicrm-core#29013 for this

@colemanw thoughts?

**Comment by totten** [comment]
Yeah, `hook_civicrm_entityTypes` has historically been a bit ornery about timing/ordering. It sounds like https://github.com/civicrm/civicrm-core/pull/29013 (cc @jensschuppe) and https://github.com/civicrm/civicrm-core/pull/29014/ (cc @colemanw) would both make `hook_civicrm_entityTypes` more forgiving about when/how you register more entities. That's neat.
 
My gut says that 29013 and 29014 put the `flush()` a bit too early -- we still don't have all the listeners yet.

* For example, `CRM_Utils_Hook::container()` can also be used to register listeners via `findDefintion()` + `addMethodCall()`
* With service-tags and compile-passes, you won't have all listeners registered until (*at best*) `$containerBuilder->compile()` runs the main passes (`AutoServiceScannerPass`, `EventScannerPass`, `RegisterListenersPass`). 
* Even then, those listeners won't be *invokable* until the container is actually instantiated ([typical moment](https://github.com/civicrm/civicrm-core/blob/fa1fd627d166c3c774cf21d73ab25d430b4e8bb8/Civi/Core/Container.php#L89) or [less typical moment](https://github.com/civicrm/civicrm-core/blob/fa1fd627d166c3c774cf21d73ab25d430b4e8bb8/Civi/Core/Container.php#L67))

A simple way to guarantee that it fires later would be [placing it at the end of bootstrap](https://github.com/civicrm/civicrm-core/compare/master...totten:civicrm-core:master-entitytype-flush?expand=1). This placement would mean that it clears+fires on every page-request (*which may be good or bad*).

Then again... maybe either 29013 or 29014 is fine, because the exact placement of `flush()` is less important than the placement of the *re-hydration step*. The catch is that re-hydration is ambiguous -- and `flush()` is the part we can see. (*We know re-hydration comes after `flush()`, but other/future parties can unwittingly trigger the re-hydrate in diff ways.*) I guess one could [strictly enforce that re-hydration comes later](https://github.com/civicrm/civicrm-core/compare/master...totten:civicrm-core:master-entitytype-restrict?expand=1).

One other idea - for dynamic entities, you might try a different pattern. Use some other event and register via [`AllCoreTables::registerEntityType()`](https://github.com/civicrm/civicrm-core/blob/b192a823a03bbd201b60c82f86abca63c978ac80/CRM/Core/DAO/AllCoreTables.php#L75). For example (*untested*):

```php
use CRM_Core_DAO_AllCoreTables as AllCoreTables;

function hook_civicrm_config($config, ?array $flags = NULL) {
  if ($flags === NULL || !empty($flags['civicrm'])) {
    // Ensure that the baseline was already initialized.
    AllCoreTables::init();
    
    // Add our dynamic entities.
    AllCoreTables::registerEntityType('Eck_First', 'CRM_Eck_DAO_Entity', 'civicrm_eck_first');
    AllCoreTables::registerEntityType('Eck_Second', 'CRM_Eck_DAO_Entity', 'civicrm_eck_second');
    AllCoreTables::registerEntityType('Eck_Third', 'CRM_Eck_DAO_Entity', 'civicrm_eck_third');
  }
}
```

(`hook_config` fires after the container has booted, so it would work with any style of `Subscriber`. The event still fires before any real work is done. It doesn't require re-populating `AllCoreTables` multiple times. The pattern should work with at least 5.57 -- maybe 5.48 -- possibly further back. `registerEntityType()` is currently labeled "quasi-private" --  but if it actually works better, then maybe we bless it as fully-public..)

**Comment by jensschuppe** [comment]
Thanks a lot, @totten for your thougths! I also think it might still make sense to register ECK entities manually, because for event listeners on the `\CRM_Eck_BAO_Entity` class to be registered, the class must be known to the container, which requires re-creating the entity type cache after the class has been registered as the controller for ECK entities by `\CRM_Eck_BAO_EckEntityType::hook_civicrm_entityTypes`, and also re-creating the container, doesn't it?

There is a `HookInterface`-style event listener on that class (`\CRM_Eck_BAO_Entity::on_hook_civicrm_post`) that seems to always be in place when it's needed, but others might not be - I'm not sure what triggers the second container creation.

**Comment by totten** [comment]
> ...`\CRM_Eck_BAO_EckEntityType::hook_civicrm_entityTypes` ... `\CRM_Eck_BAO_Entity::on_hook_civicrm_post` ...

Oh, wild. I didn't notice how that was arranged. So the idea is for the first BAO to add a listeners(`EckEntityType::hook_civicrm_entityTypes`) which registers new entities... which then have another BAO... with other listeners (`Entity::on_hook_civicrm_post`). More thoughts, no particular order:

* I'm not certain how that worked before. (Hypothetically, re-creating the container could make it work, though I wouldn't expect that to happen in ordinary usage, and it would seem heavy-handed.)

* My earlier concrete suggestions probably don't work. Consider re:`hook_civicrm_config`+`registerEntityType()` -- `hook_civicrm_config` comes too late for you take advantage of the BAO-scanner. So then you'd have to [manually scan BAO listeners](https://gist.github.com/totten/79b60bc94598fd9373c51171bd32a7b4)... which is getting more complicated...

* New ideas...

* ___The simplest thing is probably...___ move `CRM_Eck_BAO_EckEntityType::hook_civicrm_entityTypes()` to the top-level `eck_civicrm_entityTypes()`. 
    * Then all your concrete entities can be registered in the first go, and the BAOs would be apparent during container-setup.
    * To my eye, the aesthetics seem just as good in this situation, and it should be more compatible (backward+forward) than status-quo.

* __The second simplest thing is probably...__ move  `\CRM_Eck_BAO_Entity::on_hook_civicrm_post` to an [AutoService](https://docs.civicrm.org/dev/en/latest/framework/services/#automatic) (e.g. `Civi\Eck\RecentItems::on_hook_civicrm_post`).
    * Then your event-listeners aren't tied-up with the BAO/entity registration.
    * To my eye, the aesthetics seem just as good (*arguably better*) in this situation, and it should be more forward-compatible than status-quo. (IIRC, backward-compatibility would only go to 5.55.)

**Comment by colemanw** [comment]
Those suggestions makes sense @totten. Although I think your "how it's arranged" description overstates the cascading-ness of the hooks - it's not like one hook registers another hook or anything super-weird like that. The reality here is that ECK entities are declared using the standard/recommended `hook_civicrm_entityTypes` so I think the way that hook is registered (via BAO+`HookInterface` instead of traditional "Drupal-style" global fn) is the only problem here.

Perhaps we need to document somewhere that `HookInterface` is not suitable for all hooks, and any hooks that do early-bootstrap-stuff must be registered in a different way.

**Comment by totten** [comment]
Good idea about updating docs @colemanw.

MR: https://lab.civicrm.org/documentation/docs/dev/-/merge_requests/1147

Aside:

* It's not so much about `HookInterface`. You'd get similar caveats in `EventSubscriberInterface`, `Civi::dispatcher()`, and CMS-based listeners. (Really, everything except the extension-main-file will have a caveat.)
* AFAIK, the only other hook that has similar quirkiness is `hook_config`. But the shape is fairly different. (I guess we should update that doc too, but it'll look different.)

**Comment by colemanw** [comment]
Thanks @totten - glad we solve the mystery without a core patch!
