### ISSUE TITLE
API Entity Name Conflicts

### ISSUE THREAD

**Issue by colemanw** [systopia/de.systopia.eck#16]
An `EckEntityType` can have any string as the `name`, which could be a problem.

Consider this scenario:
1. Create an `EckEntityType` with `'name' => 'EntityType'`.
2. This will create a virtual API entity named `EckEntiyType`
3. Oops, that name is already taken.

In core, we have the same problem with virtual APIv4 entities created from custom field sets. The problem is solved by adding an underscore. So every custom virtual entity begins with `Custom_`. If we employed that solution here, then an eckType named `EntityType` would create a virtual entity named `Eck_EntiyType` and there would be no name conflict.

**Comment by jensschuppe** [comment]
Fair point, which we were aware of but didn't care for in the first draft ;-).

Wouldn't it be sufficient to only check for the entity type name not being `EntityType` (which would cause a collision, because the prefix is currently `Eck`, not `EckEntity`, btw.), or even a more general check for collisions with all entity types?

Of course, we could do like Core does with `Custom_` entities and prefix all ECK entity types with `Eck_` (instead of `Eck` currently).

I'm not sure right now, but the `Eck_` method seems more robust and in line with what Core does with `Custom_`. Maybe it should then be `ECK_` (all uppercase since it's an abbreviation for three words, as in e.g. `UFMatch`).

Note that there's already some validation code to enforce PascalCase (well, not really) in https://github.com/systopia/de.systopia.eck/blob/a8add69b3f64e8303bdbfbe82c34de9c6159bcb4/CRM/Eck/Form/EntityType.php#L170 which should be moved to the API or the BAO, of course, and not allow anything else but letters (e.g. no underscores if we went with `ECK_`).

**Comment by colemanw** [comment]
My vote would be for `Eck_` as the prefix. It's consistent with the current case convention (e.g. `EckEntity`, `EckEntityType`) and is similar to the `Custom_` prefix in core.

If you agree, I'll do a PR for that once #18 is merged.

**Comment by jensschuppe** [comment]
The user won't have to bother with API entity naming anyway, so I think that's not worth any more discussion. So just go ahead with what you prefer.

**Comment by jensschuppe** [comment]
Note that with the `_` in the name, no APIv3 calls work anymore because of `\CRM_Core_DAO_AllCoreTables::convertEntityNameToCamel()` being called in `\Civi\API\Request::create()`.

I'm not sure how to handle that ... @colemanw?

**Comment by colemanw** [comment]
@jensschuppe I've done some testing and analysis: #26
Please correct me if I'm wrong, but APIv3 appears to have already been broken before this change. I don't think it ever worked.

**Comment by jensschuppe** [comment]
As pointed out in #26 ([comment](https://github.com/systopia/de.systopia.eck/pull/26#issuecomment-1055192442)), let's work towards removing APIv3, but keep a working version with APIv3 and without the naming change.

I cherry-picked and adapted your PR commits to the [`release/1.x`](https://github.com/systopia/de.systopia.eck/tree/release/1.x) branch, but left out the re-naming PR #20.

**Comment by jensschuppe** [comment]
Since this works without APIv3 now and has an upgrade path, let's get that in for a `1.0` release
