### ISSUE TITLE
Support bridge entities

### ISSUE THREAD

**Issue by michaelmcandrew** [systopia/de.systopia.eck#87]
We have been using ECK with the new entity reference field and are exploring how we can create many to many relationships. For example lets imagine we want to allow cases to be associated with one or more events (and visa versa). What we want to happen is when you select events as the entity in searchkit, you can then be able to select cases as a 'with' entity.

For a many to many in SQL you would typically create a table with two FKs that contains the ids of each entity. You can do something like this in ECK by creating a new entity (lets call is CaseEvent) and then adding two entity reference custom data fields to that table. But searchkit doesn't like this.

Having chatted with coleman, we think the two things that SK doesn't like are:

1. the entity is not registered as a bridge entity
2. the FKs are on attached to custom data, not the original entity.

Thinking about how to approach solving this in ECK, we could (thanks @colemanw for your ideas)

1. Introduce a "type" to the ECK entity that includes "Regular Entity" and "Bridge Entity"
2. When creating a bridge entity, the user would need to select 2 entities to bridge. This would add an extra couple of fields to the entity
3. It might also make sense to allow them to select between "one" and "many" for each side of the bridge (so you could create a "one to one" bridge, a "one to many" bridge or a "many to many" bridge) - need to think some more on 

Also from coleman:

> Note: last time I checked, APIv4/SK are a little buggy if both entities are the same (e.g. a bridge between "Activity" and "Activity" may confuse the API). 

> (untested) it may be possible to keep ECK simple and use custom fields instead of adding all the schema handling logic in ECK. In that case, the custom value table itself would be the bridge (and the eck table would be useless, so, bleh).

One final thought from me: title and subtype often don't make sense for bridge entities. we should consider making them optional in this case.

**Comment by bjendres** [comment]
Sounds great to me! 

FYI I'm sure @jensschuppe will also have an opinion on this, but he's currently on holiday.

**Comment by jensschuppe** [comment]
> it may be possible to keep ECK simple and use custom fields instead of adding all the schema handling logic in ECK. In that case, the custom value table itself would be the bridge (and the eck table would be useless, so, bleh).

Well, actually the custom value table already is - structurally - a bridge when there is at least one contact or entity reference field in that custom group, at least the FKs are there. So re-using this seems somewhat obvious.

For "pure" bridge entities, their ECK table would really be kind of useless, unless you want to use the entity for more semantics, like adding a note about the "relatedness" of e. g. cases and events, or even another reference, like a coordinating contact or whatever comes to mind.

@colemanw Would you think that implicitly defining generic SearchKit bridges for all contact/entity reference fields would be reasonable, at least between all linked entities within a custom group, or between the entity the custom group is attached to and each referenced entity?

@michaelmcandrew have you thought of trying to implement your scenario using multi-value custom groups? As they behave similar to custom entities and are available as entities in SearchKit, this might be worth a try. At least they "magically" turn into entities without the need to manually create an ECK entity type with a useless table. Of course, this would require to pick one of the entities (case, event) to attach them to.

**Comment by michaelmcandrew** [comment]
> For "pure" bridge entities, their ECK table would really be kind of useless, unless you want to use the entity for more semantics

Agreed - it would be nice not to _have to_ add a title and a type for a bridge entity. That said, I can imagine quite a few scenarios where people would want to add semantics about the bridge and it feels like a good feature to have in something like ECK.

aside: I think it would be a nice feature for ECK in general to not have to define types and titles for the simplest entities - is there any reason why both are required?

One thing I find interesting is that Searchkit already picks up the referenced entity in the other direction even though the reference is in a custom data table. Extending the EventCase example above, if you start with the EventCase entity, both events and cases can be selected as 'with entities' even though they entity references are in a custom data set.

> have you thought of trying to implement your scenario using multi-value custom groups?

Interesting thought! I hadn't. I have always thought of multivalue custom data as a bit 'weird' and just connected to contacts, though i appreciate that that may be more of a UI thing and maybe I am being unfair. Experimenting just now with creating a table, I can see that the custom value table it created looks similar like a many to many table. But although I can find the custom data in SK, I don't seem to be able to join though to the other side.

I certainly wouldn't be against this approach but I wonder how much further it gets us and I like the idea of creating a simple and robust solution 'the right way'.

@colemanw - interested in your thoughts on what would be easiest and most robust.

**Comment by jensschuppe** [comment]
> I think it would be a nice feature for ECK in general to not have to define types and titles for the simplest entities - is there any reason why both are required?

I chose to have the title required so that the entity ID (which is not really visible in the UI) would not be the only thing to make an entity; the title is also the `label_column` of those entities.

"Bridge" entity types wouldn't need a title, but this would also imply that "bridge" entities would need something else for them to be displayed.

Types are required as every ECK entity type is an entity itself and defines the DB table, API entity, etc. Sub-types being required is kind of an architectural thing we adopted from Drupal entities (*bundles*) and also for making code easier, see #5 for our discussion around that.

> I certainly wouldn't be against this approach but I wonder how much further it gets us and I like the idea of creating a simple and robust solution 'the right way'.

Don't get me wrong, I'd really like to have this in *ECK* (or somewhere), too. It's just that ECK entities and multi-value custom groups are very similar concepts and maybe there's a more generic approach that covers both. I'd really like to hear @colemanw's thoughts as well - especially because I'm not that familiar with *SearchKit* internals and Custom Group behavior in this regard.

**Comment by colemanw** [comment]
I just want to pause and take stock of what's already possible with Civi out of the box:

If you want to create a many-to-one join (for example, each Event can be associated with one or more Cases) you'd do this:
1. Add a custom EntityReference field belonging to Cases referencing Event.
2. Make a SearchKit search for e.g. Events (it would also work the other way).
3. Add an explicit join on Cases (available in the "With:" dropdown [since this PR](https://github.com/civicrm/civicrm-core/pull/26192)).
4. Perform grouping and aggregation however you want.

I think that covers most use-cases rather nicely, as many-to-many is a comparatively scenario.

To achieve many-to-many, we could expand on that scenario and use a multi-record custom group. I tried this out locally with the following steps:
1. Add a multi-record custom group called "Custom Bridge"
2. Add an entityRef field to "Event" called "Manager"
3. Now we effectively have a many-to-many relationship. Multiple contacts can be the "Manager" of multiple events. Yay!
4. Then I tried to use it in SearchKit and the results were reasonable but not quite what you want:

![image](https://github.com/systopia/de.systopia.eck/assets/2874912/871fcbc2-cd4c-4061-a635-b9c9c5e68b4c)

In order to meet all your expectations, we'd need to make the following general improvements in Core/SearchKit.

- Allow multi-record custom fields for any entity, not just Contact
- Teach SearchKit to join through multi-record custom data (for some reason that wasn't covered in [this PR](https://github.com/civicrm/civicrm-core/pull/26192)).
- Teach APIv4 to auto-flag a multi-record custom field set as a bridge entity if it has an EntityRef field.

I like the idea of making these improvements in general as they'd improve SK custom data all-around and not just for the bridge use-case.

**Comment by michaelmcandrew** [comment]
Thanks for your engagement with this @jensschuppe and @colemanw - the client we are working with this on is away on holiday at the mo but I'll chat with them and we will reply on this when they are back.

**Comment by colemanw** [comment]
Note that I've added to core the ability for [multi-record custom data groups to be attached to any entity](https://github.com/civicrm/civicrm-core/pull/27549).

**Comment by michaelmcandrew** [comment]
That's great Coleman - have just got back onto this this week. I have been experimenting with defining joins and looking at bridge entities, etc. With a bit of luck I'll have some sensible questions and suggestions for moving this foward in the next day or two.

**Comment by michaelmcandrew** [comment]
Hey Jenn and Coleman - I'm looking into this today. For the moment, I am investigating the multivalue custom data route.

I'm looking at the Civi\Search\Admin::getJoins() function, e.g. https://github.com/civicrm/civicrm-core/blob/master/ext/search_kit/Civi/Search/Admin.php#L287.

It feels promising and seems likely that we won't need to add bridge entity support here.

**Comment by colemanw** [comment]
This should fix that TODO: https://github.com/civicrm/civicrm-core/pull/28720

**Comment by michaelmcandrew** [comment]
In case people are following along, here is a patch for core which bypasses ECK: https://github.com/civicrm/civicrm-core/pull/28721 :crossed_fingers:

**Comment by michaelmcandrew** [comment]
I created a post in chat https://chat.civicrm.org/civicrm/pl/sqf3bfdrzp8omckrpz48p1k5fa and an issue in gitlab to try and generate a bit more interest around this as I think it is worth shouting about: https://lab.civicrm.org/dev/core/-/issues/4899

**Comment by jensschuppe** [comment]
Thanks @michaelmcandrew for putting together your findings!
